[theme]
base = "dark"
primaryColor = "#F4C21A"
backgroundColor = "#0A0A0B"
secondaryBackgroundColor = "#141416"
textColor = "#FFFFFF"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#0A0A0B"
secondaryBackgroundColor = "#141416"
textColor = "#FFFFFF"

[client]
toolbarMode = "minimal"
